name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container: node:16-bullseye
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: yarn build

      - name: Test
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
        run: yarn test
