name: Checks (trusted)

on:
  workflow_run:
    workflows: ["Checks (untrusted)"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflows triggered by Dependabot don't have access to GitHub secrets, so the checks that need
# access to the secrets have to be run in a separate workflow.
# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build
        env:
          DATABASE_URL: ${{ secrets.POSTGRESQL_RAILWAY }}
        run: yarn build

      - name: Test
        env:
          DATABASE_URL: ${{ secrets.POSTGRESQL_RAILWAY }}
        run: yarn test
