name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build
        env:
          DATABASE_URL: ${{ secrets.POSTGRESQL_RAILWAY }}
        run: yarn build

      - name: Test
        env:
          DATABASE_URL: ${{ secrets.POSTGRESQL_RAILWAY }}
        run: yarn test
